version: '3'
services:
  anigiri-db:
    build: './anigiri-db'
    expose:
      - '3306'
    # 注) データを永続化する為にホスト側に"~/data/anigiri/mysql"ディレクトリを用意する必要がある。
    volumes:
      - './data/mysql:/var/lib/mysql'

  anigiri-crawler:
    build: './anigiri-crawler'
    links:
      - 'anigiri-db'

  anigiri-web:
    build: './anigiri-web'
    ports:
      - '80:80'
      - '8080:8080'
    links:
      - 'anigiri-db'
    volumes:
      - './log/web:/var/log/anigiri'
    command: gradle bootRun
    # "docker-compose --compatibility xxx"とすることで以下設定を有効化できる。
    deploy:
      resources:
        limits:
          memory: 600m

