version: '3'
services:
  # "docker-compose run --service-ports anigiri-xxx"とすることでports設定が反映される。
  anigiri-db:
    build: './anigiri-db'
    ports:
      - '13306:3306'
    volumes:
      - './data/mysql:/var/lib/mysql'

  anigiri-crawler:
    build: './anigiri-crawler'
    links:
      - 'anigiri-db'

  anigiri-web:
    build: './anigiri-web'
    ports:
      - '8080:8080'
    links:
      - 'anigiri-db'
    volumes:
      - './log/web:/var/log/anigiri'
    command: ./gradlew bootRun

