version: '3'
services:
  anigiri-db:
    build: './anigiri-db'
    expose:
      - '3306'
    volumes:
      - './data/mysql:/var/lib/mysql'

  anigiri-crawler:
    build: './anigiri-crawler'
    links:
      - 'anigiri-db'

  anigiri-web:
    build: './anigiri-web'
    ports:
      - '80:80'
    links:
      - 'anigiri-db'
    volumes:
      - './log/web:/var/log/anigiri'
    command: ./gradlew bootRun -Penv=pro

